---
- name: Install needed apt packages for pyenv
  sudo: true
  apt:
    name={{ item }}
    state=installed
  with_items:
    - zlib1g-dev
    - libreadline-dev
    - libbz2-dev
    - libsqlite3-dev
    - libssl-dev
- name: Install pyenv
  git:
    repo=https://github.com/yyuu/pyenv.git
    dest={{ home }}/.pyenv
- name: Set pyenv settings in ~/.bashrc_mods
  lineinfile:
    line='{{ item }}'
    insertafter=EOF
    dest={{ home }}/.bashrc_mods
  with_items:
    - "export PYENV_ROOT=$HOME/.pyenv"
    - "export PYENV_SHELL=bash"
    - "export PATH=$PYENV_ROOT/bin:$PATH"
    - "eval \"$(pyenv init -)\""
- name: Install Python {{ python_version }}
  shell:
    pyenv install {{ python_version }}
    creates={{ home }}/.pyenv/versions/{{ python_version }}
  environment:
    PYENV_ROOT: "{{ home }}/.pyenv"
    PYENV_SHELL: "bash"
    PATH: "{{ home }}/.pyenv/bin:$PATH:/usr/bin:/bin:$PATH"
- name: Set python {{ python_version }} as global version
  shell:
    pyenv global {{ python_version }}
    creates={{ home }}/.pyenv/version
  environment:
    PYENV_ROOT: "{{ home }}/.pyenv"
    PYENV_SHELL: "bash"
    PATH: "{{ home }}/.pyenv/bin:$PATH:/usr/bin:/bin:$PATH"
