---
- name: Install needed apt packages for pyenv
  sudo: true
  apt:
    name={{ item }}
    state=installed
  with_items:
    - zlib1g-dev
    - libreadline-dev
    - libbz2-dev
    - libsqlite3-dev
    - libssl-dev
- name: Install pyenv
  git:
    repo=https://github.com/yyuu/pyenv.git
    dest={{ home }}/.pyenv
- name: Set pyenv settings in ~/.bashrc_mods
  lineinfile:
    line='{{ item }}'
    insertafter=EOF
    dest={{ home }}/.bashrc_mods
  with_items:
    - "export PYENV_ROOT=$HOME/.pyenv"
    - "export PATH=$PYENV_ROOT/bin:$PATH"
    - "eval \"$(pyenv init -)\""
